
version: '3'

services:
  taskhelper-pg:
    image: bitnami/postgresql
    ports: 
      - 5433:5432
    environment:
      - POSTGRES_USER=root 
      - POSTGRES_PASSWORD=root
      - POSTGRES_DATABASE=taskhelper